# Generated by Django 4.2.5 on 2023-09-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.IntegerField(default=0),
        ),
    ]
