# Generated by Django 4.2.5 on 2023-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_users_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='busprofile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
