# Generated by Django 4.2.5 on 2023-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_busdetails_link_remove_busdetails_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='busname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
