# Generated by Django 4.2.5 on 2023-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_busdetails_busname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hotelname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
