# Generated by Django 4.2.5 on 2023-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_users_hotelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hoteladdress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
