# Generated by Django 4.2.5 on 2023-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_users_hoteladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=100, null=True)),
                ('hotelname', models.CharField(max_length=100, null=True)),
                ('fromplace', models.CharField(max_length=100, null=True)),
                ('toplace', models.CharField(max_length=100, null=True)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
