# Generated by Django 4.2.5 on 2023-10-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_package_bus_id_package_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
