# Generated by Django 4.2.5 on 2023-10-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_package_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
