# Generated by Django 4.2.5 on 2023-10-30 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_package_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('no_ppl', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('pkg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.package')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
