# Generated by Django 4.2.5 on 2023-11-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='roomname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
