# Generated by Django 4.2.5 on 2023-11-01 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_hoteldetails_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.hoteldetails'),
        ),
    ]
