# Generated by Django 4.2.5 on 2023-11-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_package_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pkg_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
