# Generated by Django 4.2.5 on 2023-11-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_package_pkg_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldetails',
            old_name='busprofile',
            new_name='roomprofile',
        ),
    ]
