# Generated by Django 4.2.5 on 2023-11-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_rename_busprofile_hoteldetails_roomprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
