# Generated by Django 4.2.5 on 2023-11-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_bookings_status_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
